"""empty message

Revision ID: f79f15ba4bb2
Revises: 48401410540e
Create Date: 2021-06-30 20:05:26.909111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79f15ba4bb2'
down_revision = '48401410540e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grade_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade_year', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
